name       : perl-test-warn
version    : '0.35'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BIGJ/Test-Warn-0.35.tar.gz : 24e410963cc8a3bf76851f475e322e1d232ea93d73d700f6b9e7888201b354c5
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Warn - Perl extension to test methods for warnings
description: |
    This module provides a few convenience methods for testing warning based code.
builddeps  :
    - perl-sub-uplevel
rundeps    :
    - perl-sub-uplevel
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
