name       : perl-test-warn
version    : 0.32
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BIGJ/Test-Warn-0.32.tar.gz : 2fc516e71f9ef453be22a4619d91eb3f78df414a57dfa0fd745d3bff50bf73d2
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Warn - Perl extension to test methods for warnings
description: |
    This module provides a few convenience methods for testing warning based code.
builddeps  :
    - perl-sub-uplevel
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
