name       : perl-test-warn
version    : '0.37'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BIGJ/Test-Warn-0.37.tar.gz : 98ca32e7f2f5ea89b8bfb9a0609977f3d153e242e2e51705126cb954f1a06b57
homepage   : https://metacpan.org/pod/Test::Warn
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Warn - Perl extension to test methods for warnings
description: |
    This module provides a few convenience methods for testing warning based code.
builddeps  :
    - perl-sub-uplevel
rundeps    :
    - perl-sub-uplevel
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
