name       : perl-test-warn
version    : '0.36'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BIGJ/Test-Warn-0.36.tar.gz : ecbca346d379cef8d3c0e4ac0c8eb3b2613d737ffaaeae52271c38d7bf3c6cda
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Warn - Perl extension to test methods for warnings
description: |
    This module provides a few convenience methods for testing warning based code.
builddeps  :
    - perl-sub-uplevel
rundeps    :
    - perl-sub-uplevel
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
